# Generated by Django 5.2.9 on 2025-12-17 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="template_version",
            field=models.ForeignKey(
                default="Annex9_v2013",
                on_delete=django.db.models.deletion.PROTECT,
                to="core.template",
            ),
        ),
    ]
